# Generated by Django 2.2.2 on 2019-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dietdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(unique=True)),
                ('Deficiency', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Food', models.TextField()),
                ('Meals_per_day', models.IntegerField()),
                ('Time', models.IntegerField()),
            ],
        ),
    ]
