# Generated by Django 2.2.2 on 2019-12-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0002_auto_20191204_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietdata',
            old_name='Age_now',
            new_name='query',
        ),
    ]
