# Generated by Django 2.2.2 on 2019-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0003_auto_20191204_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietdata',
            name='Age',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='query',
            field=models.IntegerField(),
        ),
    ]
