# Generated by Django 2.2.2 on 2019-12-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0005_dietdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietdata',
            name='query',
        ),
        migrations.RemoveField(
            model_name='dietdata',
            name='user',
        ),
    ]
