# Generated by Django 2.2.2 on 2019-12-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diet', '0006_auto_20191205_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietdata',
            name='query',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dietdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
