# Generated by Django 2.2.2 on 2019-12-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0007_auto_20191205_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdata',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
