# Generated by Django 2.2.2 on 2019-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0008_auto_20191205_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdata',
            name='Food',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='Meals_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='Time',
            field=models.IntegerField(null=True),
        ),
    ]
