# Generated by Django 2.2.2 on 2019-12-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0014_auto_20191205_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdata',
            name='query',
            field=models.IntegerField(default=25),
        ),
    ]
