# Generated by Django 2.2.2 on 2019-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0017_auto_20191205_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdata',
            name='query',
            field=models.CharField(default=25, max_length=200),
        ),
    ]
