# Generated by Django 2.2.2 on 2019-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0018_auto_20191205_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietdata',
            name='query2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
