# Generated by Django 2.2.2 on 2019-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0019_dietdata_query2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietdata',
            name='query2',
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='query',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
