# Generated by Django 2.2.2 on 2019-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0020_auto_20191205_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdata',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
